name: Commit Message Validator

on:
  push:
    branches:
      - dev
      - main

jobs:
  validate-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Commit Message
        run: |
          echo "Last commit message: ${{ github.event.head_commit.message }}"
          MESSAGE="${{ github.event.head_commit.message }}"
          if [[ ! "$MESSAGE" =~ ^(feat:|fix:|docs:) ]]; then
            echo "❌ Commit message is invalid! Must start with feat:, fix: or docs:"
            exit 1
          else
            echo "✅ Commit message is valid!"
          fi
