name: HTML Deployment Simulation

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate HTML File
        run: |
          if [ ! -f index.html ]; then
            echo "❌ index.html not found!"
            exit 1
          fi
          echo "✅ index.html exists"

      - name: Create Deploy Folder
        run: mkdir deploy-folder

      - name: Copy HTML to Deploy Folder
        run: cp index.html deploy-folder/

      - name: Show Deploy Folder Content
        run: ls deploy-folder

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website-files
          path: deploy-folder/
